import { useEffect, useState } from 'react';
import { Folder, FolderCheck, Archive, Calendar, Clock } from 'lucide-react';
import { getProcessos } from '../services/api';
import type { Processo } from '../types';
export function Dashboard() {
  const [time, setTime] = useState(new Date()); const [processos, setProcessos] = useState<Processo[]>([]);
  useEffect(() => { const timer = setInterval(() => setTime(new Date()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { getProcessos().then(({ data }) => setProcessos(data)).catch(() => setProcessos([])); }, []);
  const cards = [['Projetos Ativos', processos.filter(p => p.status === 'EM_ANDAMENTO').length, Folder, 'bg-emerald-50 text-emerald-600'], ['Projetos Encerrados', processos.filter(p => ['CONCLUIDO', 'AGUARDANDO_RETIRADA', 'ENTREGUE'].includes(p.status)).length, FolderCheck, 'bg-blue-50 text-blue-600'], ['Projetos Arquivados', processos.filter(p => p.status === 'ARQUIVADO').length, Archive, 'bg-slate-100 text-slate-600']] as const;
  return <div className="space-y-6"><div className="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-200 md:p-8"><div className="flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Visão geral</p><h1 className="mt-2 text-2xl font-bold tracking-tight">Sua área de trabalho</h1><p className="mt-1 text-sm text-slate-300">Acompanhe o andamento das suas obras e processos em tempo real.</p></div><div className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-xs"><span className="flex gap-1.5"><Calendar className="w-4 h-4 text-slate-300" />{time.toLocaleDateString('pt-BR')}</span><span className="flex gap-1.5 border-l border-slate-700 pl-4"><Clock className="w-4 h-4 text-slate-300" />{time.toLocaleTimeString('pt-BR')}</span></div></div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-3">{cards.map(([label, value, Icon, color]) => <div key={label} className="surface flex items-center justify-between p-6"><div><p className="text-[11px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><h3 className="mt-1 text-3xl font-extrabold tracking-tight text-slate-950">{value}</h3></div><div className={`rounded-2xl p-3 ${color}`}><Icon className="w-6 h-6" /></div></div>)}</div></div>;
}
