import { useRef, useState } from "react";
import { Camera, Loader2 } from "lucide-react";
import { useAuth } from "../contexts/AuthContext";
import { getErrorMessage, updatePerfil, uploadFotoPerfil } from "../services/api";
const phone = (v: string) => v.replace(/\D/g, "").slice(0, 11).replace(/(\d{2})(\d)/, "($1) $2").replace(/(\d{5})(\d)/, "$1-$2");
export function PerfilPage() { const { user, setUser } = useAuth(); const [nome, setNome] = useState(user?.nome || ""), [telefone, setTelefone] = useState(phone(user?.telefone || "")), [saving, setSaving] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""); const input = useRef<HTMLInputElement>(null); if (!user) return null;
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { setSaving(true); const r = await updatePerfil({ nome, telefone: telefone.replace(/\D/g, "") }); setUser(r.data); setMessage("Perfil atualizado com sucesso."); } catch (e) { setError(getErrorMessage(e)); } finally { setSaving(false); } };
  const upload = async (file?: File) => { if (!file) return; try { setSaving(true); const r = await uploadFotoPerfil(file); setUser(r.data); setMessage("Foto de perfil atualizada."); } catch (e) { setError(getErrorMessage(e)); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-2xl space-y-6"><div><p className="eyebrow">Sua conta</p><h1 className="page-title">Perfil</h1><p className="mt-1 text-sm text-slate-500">Mantenha seus dados profissionais atualizados.</p></div><form onSubmit={save} className="surface space-y-6 p-6"><div className="flex items-center gap-5"><button type="button" onClick={() => input.current?.click()} className="relative grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-full bg-slate-900 text-2xl font-bold text-white">{user.fotoUrl ? <img src={user.fotoUrl} alt="Foto de perfil" className="h-full w-full object-cover" /> : user.nome.charAt(0).toUpperCase()}<span className="absolute bottom-0 right-0 rounded-full bg-blue-600 p-1.5 text-white"><Camera size={14} /></span></button><div><p className="font-semibold">Foto de perfil</p><p className="text-sm text-slate-500">JPG, PNG ou WebP.</p><button type="button" className="mt-2 text-sm font-semibold text-blue-600" onClick={() => input.current?.click()}>Alterar foto</button><input ref={input} className="hidden" type="file" accept="image/*" onChange={e => void upload(e.target.files?.[0])} /></div></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Nome<input required value={nome} onChange={e => setNome(e.target.value)} className="field" /></label><label className="text-sm font-semibold">Telefone<input required value={telefone} onChange={e => setTelefone(phone(e.target.value))} className="field" placeholder="(99) 99999-9999" /></label><label className="text-sm font-semibold">E-mail<input disabled value={user.email} className="field cursor-not-allowed opacity-70" /></label><label className="text-sm font-semibold">CREA / CAU<input disabled value={user.creaCau} className="field cursor-not-allowed opacity-70" /></label></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<button disabled={saving} className="button-primary">{saving && <Loader2 size={16} className="animate-spin" />}Salvar perfil</button></form></div>; }
